version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"  # FastAPI
      - "8501:8501"  # Streamlit
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
    environment:
      - DB_PATH=data/functions.db
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: unless-stopped
